---
- name: check if binary is installed
  ansible.builtin.stat:
    path: /usr/bin/gh
  register: gh_installed

- block:
    - name: get latest version
      ansible.builtin.uri:
        url: https://api.github.com/repos/cli/cli/releases/latest
        return_content: true
      register: gh_latest

    - name: get and install
      ansible.builtin.apt:
        deb: "{{ item.browser_download_url }}"
      loop: "{{ gh_latest.json.assets }}"
      when: "'linux_arm64.deb' in item.name"
      become: true
  when: not gh_installed.stat.exists
