---
- name: get and install dependencies
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-debian
    state: present
  become: true

- name: add repository
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    architectures: arm64
    state: present
    enabled: true
  become: true

- name: get and install
  ansible.builtin.apt:
    name: docker-ce
    update_cache: true
  become: true

- name: add user to docker system group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
  become: true
