---
- name: get and install packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - bash-completion
      - curl
      - file
      - tree
      - htop
      - tmux
      - jq
      - sshpass
    state: present
  become: true
