---
- name: get and install packages
  ansible.builtin.apt:
    pkg:
      - build-essential
      - bash-completion
      - curl
      - file
      - tree
      - htop
      - tmux
      - jq
      - sshpass
    state: present
  become: true

- name: limit ssh to display only error messages
  ansible.builtin.copy:
    content: |
      Host *
              LogLevel ERROR
    dest: /etc/ssh/ssh_config.d/quiet.conf
    mode: 0644
  become: true
